TestUngDung/Areas/Admin/Controllers/ProductsController.cs
//@ Nguyen Cong Thuan

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Office.CustomUI;
using MobilePhoneWord.Areas.Admin.Controllers;
using ModelEF.Model;
using TestUngDung.Areas.Admin.Models;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class ProductsController : BaseController
    {
        private NguyenCongThuanContext db;
        public ProductsController()
        {
            db = new NguyenCongThuanContext();
        }
        // GET: Admin/Products
        public ActionResult Index()
        {
            IEnumerable<Product> result = from s in db.Products
                                          orderby s.Quantity ascending, s.UnitCost descending
                                          select s;
            return View(result.ToList());
        }

        // Xem chi tiết
        public ActionResult Details(int id)
        {
            return View(db.Products.Where(s => s.ID == id).FirstOrDefault());
        }
        // Thêm sản phẩm
        [HttpGet]
        public ActionResult Create()
        {
            Product pro = new Product();

            var listCategory = new SelectList(db.Categories, "ID", "Name");
            ViewBag.IDCategoryNo = listCategory;
            
            return View(pro);
        }

        [HttpPost]
        public ActionResult Create(Product model, HttpPostedFileBase image)
        {
            try
            {
                if(image != null) // có file hình ảnh
                {
                    // lấy tên file lưu vào db
                    string fileName = Path.GetFileNameWithoutExtension(image.FileName);// tên file
                    string extension = Path.GetExtension(image.FileName);//đường dẫn (duoi)
                    fileName = fileName + extension;
                    model.Image = "~/Contents/Images/" + fileName;
                    image.SaveAs(Path.Combine(Server.MapPath("~/Contents/Images/"), fileName)); // mappath lưu vào folder
                }
                db.Products.Add(model);
                db.SaveChanges();

                return RedirectToAction("Index"); // tạo xong điều hường đến trang Index
            }
            catch
            {
                return View();
            }
        }

    }
}

TestUngDung/Areas/Admin/Controllers/UserController.cs
//@ Nguyen Cong Thuan

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.DAO;
using ModelEF.Model;
using TestUngDung.Extensions;
using PagedList;
using MobilePhoneWord.Areas.Admin.Controllers;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class UserController : BaseController
    {
        // GET: Admin/User
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var user = new userDAO();
            var model = user.ListAllPaging(page, pageSize);
            return View(model);
        }
        // tìm kiếm theo userName
        [HttpPost]
        public ActionResult Index(string searchName, int? page)
        {
            var db = new NguyenCongThuanContext();
            int recordsPerPage = 5;

            if (!page.HasValue)
            {
                page = 1; // đặt giá trị trang ban đầu
            }
            ViewBag.Keyword = searchName;

            var listUser = db.UserAccounts.ToList();
            try
            {
                if (!String.IsNullOrEmpty(searchName))
                {
                    listUser = listUser.Where(s => s.UserName.Contains(searchName)).ToList();
                    if(listUser.Count <= 0)
                    {
                        this.AddNotification("Không tìm thấy tài khoản nào!", NotificationType.ERROR);
                    }
                }
            }
            catch (Exception ex) {}
            listUser.OrderBy(v => v.ID);

            var finalList = listUser.ToPagedList(page.Value, recordsPerPage);
            return View(finalList);
        }
        // Xóa
        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int id)
        {
            var context = new NguyenCongThuanContext();
            var deleting = context.UserAccounts.Find(id);
            
            return View(deleting);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var context = new NguyenCongThuanContext();
                var deleting = context.UserAccounts.Find(id);
                context.UserAccounts.Remove(deleting);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestUngDung/Areas/Client/Controllers/SalesController.cs
//@ Nguyen Cong Thuan

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelEF.Model;

namespace TestUngDung.Areas.Client.Controllers
{
    public class SalesController : Controller
    {
        NguyenCongThuanContext db;

        public SalesController()
        {
            db = new NguyenCongThuanContext();
        }
        // GET: Client/Products
        public ActionResult Index()
        {

            return View(db.Products.ToList());
        }
    }
}

TestUngDung/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestUngDung/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <title>@ViewBag.title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Assets/Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <script src="~/Scripts/scripts.js"></script>

    <!-- Custom styles for this template-->
    <link href="~/Assets/Admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @Html.Partial("_Sidebar")
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Nhập từ khóa cần tìm kiếm..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell fa-fw"></i>
                                <!-- Counter - Alerts -->
                                <span class="badge badge-danger badge-counter">3+</span>
                            </a>
                            <!-- Dropdown - Alerts -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="alertsDropdown">
                                <h6 class="dropdown-header">
                                    Thông Báo
                                </h6>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="mr-3">
                                        <div class="icon-circle bg-primary">
                                            <i class="fas fa-file-alt text-white"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="small text-gray-500">December 12, 2019</div>
                                        <span class="font-weight-bold">Hi, Nguyễn Công Thuận. Chúng tôi không thấy giá trị đặt cho phần settings!</span>
                                    </div>
                                </a>
                               
                                <a class="dropdown-item text-center small text-gray-500" href="#">Hiển Thị Tất Cả Thông Báo</a>
                            </div>
                        </li>

                        <!-- Nav Item - Messages -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-envelope fa-fw"></i>
                                <!-- Counter - Messages -->
                                <span class="badge badge-danger badge-counter">7</span>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="messagesDropdown">
                                <h6 class="dropdown-header">
                                    Thư Điện Tử
                                </h6>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                                             alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">
                                            Tôi có phải là một cậu bé tốt không? Lý do tôi hỏi là vì ai đó đã nói với tôi rằng mọi người nói điều này với tất cả các con chó, ngay cả khi chúng không tốt ...
                                        </div>
                                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                                    </div>
                                </a>
                                <a class="dropdown-item text-center small text-gray-500" href="#">Đọc Thêm Tin Nhắn</a>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                    Xin chào,
                                    @if (Session["FullName"] != null)
                                    {
                                        @Session["FullName"].ToString()}
                                </span>
                                <img class="img-profile rounded-circle"
                                     src="~/Assets/Admin/images/Admin.jpg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Hồ Sơ
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Cài Đặt
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Hoạt Động Đăng Nhập
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng Xuất
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">@RenderSection("header", required: false)</h1>

                    </div>
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->
               
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn Có Chắc Chắn Muốn Rời Khỏi?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Chọn "Đăng xuất" bên dưới nếu bạn đã sẵn sàng kết thúc phiên hiện tại của mình.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy Bỏ</button>
                    <a class="btn btn-primary" href="@Url.Action("Logout","Home")">Đăng xuất</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Assets/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Assets/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Assets/Admin/js/sb-admin-2.min.js"></script>

</body>

</html>

TestUngDung/Areas/Admin/Views/Shared/_Sidebar.cshtml
@{
    Layout = null;
}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Index","Home")">
            <i class="fa fa-home" aria-hidden="true"></i>
            <span>Trang Chủ</span>
        </a>
    </li>

    <!-- Divider -->
    @*Phần cho Admin*@
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Admin
    </div>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","User")">
            <i class="fas fa-user"></i>
            <span>Tài Khoản</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","Products")">
            <i class="fa fa-book" aria-hidden="true"></i>
            <span>Sản Phẩm - Sách</span>
        </a>
    </li>
    @*Phần cho Client*@
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Client
    </div>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","Sales", routeValues: new { Area = "Client"})">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <span>Trang Bán Hàng</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>


</ul>